spring:
  datasource:
    url: jdbc:postgresql://database-2.cafqer3yrdii.eu-central-1.rds.amazonaws.com:5432/sample_database?ssl=true&sslmode=require&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: postgres
    initialization-mode: always
cloud:
  aws:
    credentials:
      instance-profile: true
    region:
      static: eu-central-1
    stack:
      auto: false
